In [2]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
pd.__version__

'1.3.4'

In [4]:
df = pd.read_csv('master_housing_data.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [5]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [6]:
df.ocean_proximity.nunique()

5

In [7]:
df['ocean_proximity'] = "NEAR BAY"
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635        NEAR BAY  
20636        NEAR BAY  
20637        NEAR BAY  
20638        NEAR BAY  
20639        NEAR BAY  

[20640 rows x 10 columns]

In [8]:
df[
    df['ocean_proximity'] == "NEAR BAY"
].describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [9]:
#median house value Near Bay mean = 259212

In [10]:
#average total bedrooms: 537.87
df_bedrooms = df.fillna(537.8706)
df_bedrooms.describe().round(4)

longitude    latitude  housing_median_age  total_rooms  \
count  20640.0000  20640.0000          20640.0000   20640.0000   
mean    -119.5697     35.6319             28.6395    2635.7631   
std        2.0035      2.1360             12.5856    2181.6153   
min     -124.3500     32.5400              1.0000       2.0000   
25%     -121.8000     33.9300             18.0000    1447.7500   
50%     -118.4900     34.2600             29.0000    2127.0000   
75%     -118.0100     37.7100             37.0000    3148.0000   
max     -114.3100     41.9500             52.0000   39320.0000   

       total_bedrooms  population  households  median_income  \
count      20640.0000  20640.0000  20640.0000     20640.0000   
mean         537.8706   1425.4767    499.5397         3.8707   
std          419.2666   1132.4621    382.3298         1.8998   
min            1.0000      3.0000      1.0000         0.4999   
25%          297.0000    787.0000    280.0000         2.5634   
50%          438.0000   1166.0000    409.0000         3.5348   
75%          643.2500   1725.0000    605.0000         4.7432   
max         6445.0000  35682.0000   6082.0000        15.0001   

       median_house_value  
count          20640.0000  
mean          206855.8169  
std           115395.6159  
min            14999.0000  
25%           119600.0000  
50%           179700.0000  
75%           264725.0000  
max           500001.0000

In [11]:
df['ocean_proximity'] = "ISLAND"
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0              ISLAND  
1              ISLAND  
2              ISLAND  
3              ISLAND  
4              ISLAND  
...               ...  
20635          ISLAND  
20636          ISLAND  
20637          ISLAND  
20638          ISLAND  
20639          ISLAND  

[20640 rows x 10 columns]

In [12]:
df[
    df['ocean_proximity'] == "ISLAND"
]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0              ISLAND  
1              ISLAND  
2              ISLAND  
3              ISLAND  
4              ISLAND  
...               ...  
20635          ISLAND  
20636          ISLAND  
20637          ISLAND  
20638          ISLAND  
20639          ISLAND  

[20640 rows x 10 columns]

In [82]:
x = np.array(df[["housing_median_age","total_rooms", "total_bedrooms"]])
x = x[[0,1,2]]#possible issue?
x

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.]])

In [83]:
xtx = x.dot(x.T)
xtx

array([[  792722.,  6390655.,  1317602.],
       [ 6390655., 51619478., 10625465.],
       [ 1317602., 10625465.,  2190893.]])

In [84]:
xtxi = np.linalg.inv(xtx)
xtxi

array([[ 3.18595769e-03, -1.83516113e-05, -1.82703118e-03],
       [-1.83516113e-05,  1.15019752e-05, -4.47460078e-05],
       [-1.82703118e-03, -4.47460078e-05,  1.31624277e-03]])

In [88]:
y = np.array([950, 1300, 800])
y

array([ 950, 1300,  800])

In [89]:
w = x.T.dot(xtxi)
w

array([[ 0.03523326, -0.00283767, -0.00740332],
       [-0.00689006, -0.00013929,  0.0054888 ],
       [ 0.04355574,  0.00185209, -0.03508998]])

In [91]:
w = y.dot(w)
w

32201.642996696748